version: "3.8"
services:
  # gateway:
  #   container_name: "gateway"
  #   build:
  #     context: ./gateway
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./gateway:/home/gateway
  #     - ./gateway/node_modules:/home/gateway/node_modules
  #   environment:
  #     GATEWAY_API_PORT:
  #   depends_on:
  #     - accounts
  #   network_mode: "host"

  accounts:
    container_name: "accounts"
    build:
      context: ./accounts
      dockerfile: Dockerfile
    volumes:
      - ./accounts:/home/accounts
      - ./accounts/node_modules:/home/accounts/node_modules
    environment:
      JWT_SECRET:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      DB_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
      ACCOUNTS_API_PORT:
    ports:
      - "${ACCOUNTS_API_PORT}:${ACCOUNTS_API_PORT}"
    depends_on:
      - accounts_db
    network_mode: "host"

  accounts_db:
    build:
      context: ./accounts
    container_name: "accounts_postgresql"
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    network_mode: "host"
