federation_version: =2.3.2
subgraphs:
  accounts:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  projects:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
